pimcore:
    objects:
        select_options:
            definitions:
                InfrastructureTypes:
                    id: InfrastructureTypes
                    group: ''
                    useTraits: ''
                    implementsInterfaces: ''
                    selectOptions:
                        -
                            value: Schild
                            label: Schild
                            name: Schild
                        -
                            value: Steg
                            label: Steg
                            name: ''
                        -
                            value: Unterstand
                            label: Unterstand
                            name: ''
                        -
                            value: Furt
                            label: Furt
                            name: ''
