pimcore:
    objects:
        select_options:
            definitions:
                InfrastructureTypes:
                    id: InfrastructureTypes
                    group: null
                    useTraits: ''
                    implementsInterfaces: ''
                    selectOptions: {  }
