_pimcore:
    resource: "@PimcoreCoreBundle/config/routing.yaml"

app:
    resource: "../src/Controller/"
    type: annotation

app_localized:
    resource: "../src/Controller/"
    type: annotation
    prefix:
        en: /en
        de: /de
        cs: /cs

account-logout:
    path: '/logout'
